### ISSUE TITLE
[UE4]4.24.3 version compile error.

### ISSUE THREAD

**Issue by GitHub-NetFly** [EsotericSoftware/spine-runtimes#1631]
Version 3.8 has a compilation error in 4.24.3.

Creating a new project in 4.24.3 will trigger this problem.

Refer to this thread：http://zh.esotericsoftware.com/forum/Unreal-doesn-t-see-skel-and-atlas-13531

**Comment by badlogic** [comment]
The spine-ue4 example project compiles and works with UE 4.24.3 with both VS 2017 and VS 2019. Currently investigating compilation of new projects.
