### ISSUE TITLE
[ue] spine-ue doesn't compile with Unreal Engine 5.5

### ISSUE THREAD

**Issue by Skroopa** [EsotericSoftware/spine-runtimes#2691]
Followed [official manual](https://en.esotericsoftware.com/spine-ue#Updating-to-Unreal-Engine-5.3-), but `SpineAtlasAsset` can't compile and fails with error on the first *.uproject launch:

```
[62/96] Compile [x64] SpineAtlasAsset.cpp
D:\ue5\spine_playground\Plugins\SpinePlugin\Source\SpinePlugin\Private\SpineAtlasAsset.cpp(59): error C2039: 'UE4Ver': is not a member of 'FArchive'
```
