### ISSUE TITLE
OpenUPM does not work with Unity 2019.3

### ISSUE THREAD

**Issue by icaro56** [EsotericSoftware/spine-runtimes#1683]
Hi,

can someone help me with this? I am trying to use Spine Runtime as Package. But the version from https://openupm.com/packages/com.esotericsoftware.spine.spine-unity/ does not work with Unity 2019.3.

When I add this to my manifest, the Unity editor has many errors. The first is: 

Library\PackageCache\com.esotericsoftware.spine.spine-unity@3.8.0\Runtime\spine-unity\Asset Types\AtlasAssetBase.cs(42,19): error CS0246: The type or namespace name 'Atlas' could not be found (are you missing a using directive or an assembly reference?)

If I try to add another version of Spine in OpenUPM I get error because already exists a version there.

**Comment by icaro56** [comment]
I found the bug, but I don't know how to fix this to OpenUPM works.

The folder: spine-csharp is empty. How can I fill this folder automatically with OpenUPM?

**Comment by HaraldCsaszar** [comment]
Closing this issue as duplicate of https://github.com/EsotericSoftware/spine-runtimes/issues/1676.

**Comment by RunoLight** [comment]
Greets!

You should close openupm package either so people dont get frustrated trying to solve thing out on how to install openupm package. They believe they can if there is a package with the original author.

**Comment by HaraldCsaszar** [comment]
We did not add any of our packages to OpenUPM, the listed spine-csharp package was added by the user under "discovered by", which is user `The1Studio`. As some users might currently be using spine-csharp from OpenUPM, I am a bit hesitant to request deletion of the listing since it lists the license correctly this time.

**Comment by HaraldCsaszar** [comment]
Note that we have a whole page on installing the spine-runtimes, which does not list OpenUPM anywhere:
https://esotericsoftware.com/spine-unity-installation
For those who don't look for or can't find the documentation, I'm confident that chatGPT or any other LLM will suggest the possible ways to install it based on this documentation page.

**Comment by RunoLight** [comment]
No, it's not about "we don't know how to install it" - these users often don’t even know what GitHub is and rely on the Asset Store to get packages. The issue here is about adhering to modern standards for package import in Unity - specifically, using UPM (Unity Package Manager).

Even small startups and libraries, as well as large packages backed by big bureaucratic organizations, have adopted UPM-based importing. And I believe that’s the right approach, because it keeps the Assets folder focused solely on the actual project implementation - the parts that are meant to be modified or extended. Only those belong in the Assets directory.

**Comment by HaraldCsaszar** [comment]
From your message I assume that you're not quite aware of the currently available means of installing the spine-unity runtime and extension packages. Did you look at the installation page linked above? We provide both a unitypackage workflow (supporting versions back as far as Unity 2017.1) and UPM packages. You can install every spine-unity package via `Add package from git URL...`.

See:
https://esotericsoftware.com/spine-unity-installation#Via-Unity-Package-Manager
https://esotericsoftware.com/spine-unity-installation#B-Add-package-from-git-URL

**Comment by RunoLight** [comment]
Yes, I actually lost track of that information due to the same issue we're discussing in this thread - the one that caused the OpenUPM setup to be broken for a while. That's what initially led to the confusion.

**Comment by HaraldCsaszar** [comment]
I'm not sure I follow. To avoid potential misunderstanding: Installation via OpenUPM is not broken for a while, it's not supported at all.

Installation as documented [above](https://esotericsoftware.com/spine-unity-installation#Via-Unity-Package-Manager) via the Unity Package Manager via `Add package from git URL...` is the intended way when you want to use UPM instead of the old unitypackage way.
