### ISSUE TITLE
[sfml] example doesn't build on Debian with SFML 2.4.x

### ISSUE THREAD

**Issue by denizzzka** [EsotericSoftware/spine-runtimes#808]
Debian isn't provides SFML 2.3

with libsfml 2.4 example build fails with message:
```
libspine-sfml.a(spine-sfml.cpp.o): In function `_spAtlasPage_createTexture':
spine-sfml.cpp:(.text+0x6e): undefined reference to `sf::Texture::loadFromFile(std::string const&, sf::Rect<int> const&)'
collect2: error: ld returned 1 exit status
```

If I `apt-get purge` all libsfml 2.4 packages cmake should (probably) download SFML 2.3 binaries from www.sfml-dev.org (see CMakeLists.txt) but it isn't do that. After cmake && make I am see:
```
/usr/bin/ld: cannot find -lsfml-graphics
/usr/bin/ld: cannot find -lsfml-window
/usr/bin/ld: cannot find -lsfml-system
collect2: error: ld returned 1 exit status
```

**Comment by badlogic** [comment]
Debian doesn't have to provide 2.3, the CMakeList file in the `spine-sfml` dir will [download SFML 2.3.2](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-sfml/CMakeLists.txt#L22), there's really no way for it not to without failing. 

All you need are the dependencies as listed in the [README.md](https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-sfml#linux).

The only way for the linker to fail is if you aren't running on a 64-bit Debian. Is that the case?

**Comment by badlogic** [comment]
I've now updated `spine-sfml` to SFML 2.4.1 on all platforms (Windows, Linux, macOS) and it works as intended. Please install the dependencies as per the README.md, then delete `spine-sfml/dependencies` and `spine-sfml/build`, then `mkdir spine-sfml/build && cd spine-sfml/build && cmake ../.. && cd spine-sfml && ./spine-sfml-example`.
